### ISSUE TITLE
Feature Request: Confirm Teleport

### ISSUE THREAD

**Issue by Zemfreed** [grandseiken/foundryvtt-multilevel-tokens#69] opened 2021-03-18 14:35 UTC
I would like a functionality that asks the player or the DM or even both to confirm the teleportation.
That way if a token accidentally moved onto a teleport then there would be the option to not use it.
Or if there is a macro that does this then the code for the macro as I've not been able to find it.

**Comment by grandseiken** [comment] 2021-04-18 13:28
Good idea, but dupe of #23

**Closed by grandseiken** 2021-04-18 13:28 UTC
