### ISSUE TITLE
Teleport doesn't capture a token when it moves "through" it

### ISSUE THREAD

**Issue by ckdragons** [grandseiken/foundryvtt-multilevel-tokens#123] opened 2022-06-11 17:05 UTC
Found when a token moves through a teleporter without stopping on it, the teleport function does not work.

For example, a token is in 5 ft wide hallway, there is a teleporter 15 ft away. If the token is moved 20 ft in a single drag, the teleporter does not capture the token to move it to the new location as the token is moved.

The behavior I'd expect is the token is captured if it passes over the square, regardless of whether it stops on that square.

**Comment by grandseiken** [comment] 2022-09-03 01:17
Yep, the module only notices where tokens actually move to, it doesn't calculate mouse-drag trajectories and trigger based on that.

**Comment by grandseiken** [comment] 2022-09-03 01:43
Dupe of https://github.com/grandseiken/foundryvtt-multilevel-tokens/issues/42

**Closed by grandseiken** 2022-09-03 01:43 UTC
Labels: enhancement
