### ISSUE TITLE
Teleport creates a copy of the token for every connected player instead of just token's owner

### ISSUE THREAD

**Issue by anathemamask** [grandseiken/foundryvtt-multilevel-tokens#8] opened 2020-08-20 19:44 UTC
Steps to reproduce:

1. Create a teleport location from one scene to another
2. Connect a player account or two.
3. Move token into teleport location
4. At exit of teleport, multiple copies of the token will appear.

**Comment by grandseiken** [comment] 2020-09-06 00:50
I've been investigating this issue, and I've identified two possible scenarios in which a token teleport might end up with multiple copies coming out the other side:

1. If somebody managed to issue multiple move commands to a token in quick succession, where more than one of the movement commands ended in the teleport region. For example, if the teleport entrance was a 2x2 grid square area, and somebody double-tapped the keyboard movement keys to take two steps into it from just outside. In this case we could end up triggering the "delete-token-and-recreate-elsewhere" logic twice, if the asynchronous request to delete the token because of the first move didn't complete before the second move occurred.

2. If a single GM user is logged into the same Foundry instance from multiple different browser tabs/windows, something similar can happen: both tabs can trigger the same delete-token-and-recreate-elsewhere logic at the same time, resulting in multiple copies. (The module can deal with multiple _different_ GMs being active, and will only run as one of them, but I don't currently have an easy way of detecting whether a single GM is logged in twice.)

I've added a fix for the first case that I'll release as part of version 0.4. The second case is trickier and for now probably best just to not be logged in twice as the same GM user.

Can you let me know if it sounds like either of these cases might have been what was happening? I haven't been able to reproduce any similar issue except under the circumstances above. If you really had this problem just moving a token in via e.g. a single mouse-drag without being logged in twice under the same user I might need more details to be able to reproduce. Thanks!

**Comment by grandseiken** [comment] 2020-10-22 15:52
Closing for now since as far as I know the issue is resolved.

**Closed by grandseiken** 2020-10-22 15:52 UTC
