### ISSUE TITLE
Token issues

### ISSUE THREAD

**Issue by Linith** [grandseiken/foundryvtt-multilevel-tokens#14] opened 2020-09-17 08:19 UTC
So I am using token custom bars, token mold and cub. I believe a combination of these mods is causing a huge issue that your module is creating..

lLcSh0y698s2teZo which is a copy of a token that multi level token created.

`foundry.js:2242 Error: No actor or token exists with id 'lLcSh0y698s2teZo'
    at m.getEntity (TokenHotbar.js:1)
    at m.get (TokenHotbar.js:1)
    at T.removeTokenMacros (TokenHotbar.js:1)
    at TokenHotbar.js:1
    at Function._call (foundry.js:2239)
    at Function.call [as __furnace_original_call] (foundry.js:2224)
    at Function.callOriginalFunction (Patches.js:57)
    at Function.<anonymous> (Debug.js:42)
    at foundry.js:10380
    at Array.reduce (<anonymous>)`
Foundry VTT | Deleted 5 Tokens [lLcSh0y698s2teZo,YHtjnEChi6r12P0a,kL7AGpTLDr9MNCRD,dVHXK2lT48HUZQ3Z,4OH2TMxR6KIMqkHO] from parent Scene 0zIkmnGLn1ej4EkG

Then token mold throws up an error..
`foundry.js:2242 TypeError: Cannot read property 'data' of null
    at o._setCreatureSize (token-mold.js:537)
    at o._setTokenData (token-mold.js:257)
    at token-mold.js:240
    at Function._call (foundry.js:2239)
    at Function.call [as __furnace_original_call] (foundry.js:2224)
    at Function.callOriginalFunction (Patches.js:57)
    at Function.<anonymous> (Debug.js:42)
    at Scene.createEmbeddedEntity (foundry.js:10137)
    at multilevel.js:570`

Probably trying to get the data off the fake token multi level created.

Cub also gets into the mix trying to read the fake token..

`foundry.js:2242 TypeError: Cannot read property 'items' of null
    at Function.hasFeat (actor.js:12)
    at Function._checkForFeat (mighty-summoner.js:13)
    at Function._onPreCreateToken (token.js:30)
    at signal.js:113
    at Function._call (foundry.js:2239)
    at Function.call [as __furnace_original_call] (foundry.js:2224)
    at Function.callOriginalFunction (Patches.js:57)
    at Function.<anonymous> (Debug.js:42)
    at Scene.createEmbeddedEntity (foundry.js:10137)
    at multilevel.js:570`

**Comment by grandseiken** [comment] 2020-09-20 23:22
This is a somewhat-known issue. By necessity, MLT creates fake tokens that have no associated actor - this is something Foundry allows (you can set the "Actor" of a token to "None" in base foundry). Unfortunately, since it's not the usual case, it often trips other modules up, but there isn't much I can do about this in MLT itself.

I believe the fixes in Token Mold and CUB are simple, so I've put up PRs for those: https://github.com/Moerill/token-mold/pull/58 and https://github.com/death-save/combat-utility-belt/pull/260

I'm much less sure what's going on with the Token Hotbar module. What are you trying to do when that error shows up? It looks like the error must be coming from the `preDeleteToken` hook in Token Hotbar, but I'm not sure why that would get run for a fake token anyway.

**Comment by janssen-io** [comment] 2020-09-24 17:51
Thanks for the mention! I'm not sure why it would show this error. Are the fake tokens part of the global array of tokens (`canvas.tokens.placeables`)? I suppose I technically don't need to throw an error, but the error is nice in case there is unexpected behaviour on Token Hotbar's side. 

Apart from it filling up the console, there is nothing to worry about though. Maybe I'll change it into a warning in the meantime so it looks less severe.

**Comment by grandseiken** [comment] 2020-09-24 18:18
@janssen-io although the tokens are "fake", apart from the missing actor link they're created like any other and shouldn't behave in an observably different way.

Your mention of the canvas gave me an inkling though. `canvas.tokens.placeables` only ever stores data for tokens on the scene you are currently viewing. Because Multilevel does automation in the background, it can end up creating and deleting tokens on scenes you are not actually looking at right now. Those tokens only have data in `game.scenes.xxx.data.tokens`, they won't show up in the canvas!

**Comment by janssen-io** [comment] 2020-09-24 18:43
> [...] Because Multilevel does automation in the background, it can end up creating and deleting tokens on scenes you are not actually looking at right now. Those tokens only have data in `game.scenes.xxx.data.tokens`, they won't show up in the canvas!

Ah that must be it! I'll have to see how I can fix that problem. Ideally, I don't want to go looking through all scenes to find the token that's being deleted...

**Comment by grandseiken** [comment] 2020-10-27 20:14
Closing in favour of https://github.com/grandseiken/foundryvtt-multilevel-tokens/issues/34 which is specifically about the token hotbar issue

**Closed by grandseiken** 2020-10-27 20:14 UTC
