### ISSUE TITLE
Exporting/Importing Scenes

### ISSUE THREAD

**Issue by MrBrentRogers** [grandseiken/foundryvtt-multilevel-tokens#3] opened 2020-06-27 02:01 UTC
Created scene in another game, exported to another game. Multilevel and teleport no longer works for previously created 'drawings' but work if areas are recreated: all tokens are on different scenes.
- attempted re-entering text content
- attempted re-exporting/importing

**Comment by grandseiken** [comment] 2020-09-05 22:13
Thanks for the report. I've confirmed the issue. The problem is that the module currently checks that the special regions were created by a GM. When importing a scene into a different game, the regions remain associated with the user ID from the original game, which does not exist in the new game, so the check-for-GM part fails.

Not sure what to do about this yet. The GM check was intended so that players can't muck about with special regions themselves, but perhaps this is needlessly paranoid. I might also ask whether the imported scene ending up with invalid user IDs is intended from Foundry's perspective.

**Comment by grandseiken** [comment] 2020-09-05 22:46
Added a workaround. When importing scenes we update any drawings with invalid author IDs to use the current user's ID instead. Will be fixed in 0.4

**Closed** 2020-09-05 22:51 UTC
