### ISSUE TITLE
[Feature Request] Provide a Button (not journal note) for teleport on enter

### ISSUE THREAD

**Issue by jeremyregnerus** [grandseiken/foundryvtt-multilevel-tokens#76] opened 2021-04-13 13:37 UTC
It would be nice to provide a popup button mechanism, ideally on a token entering a transporter for activating teleports instead of using journal entries. There are many times in cramped spaces where the journal note has to be moved to a more obscure location for the players to be able to click it in tight quarters. There are also times where teleporters for hidden passages are inadvertently revealed because of where they need to be located when the players find the hidden passage. However, all journal entries the players have observer rights to appear when entering any teleporter, or turning on map notes. There are work arounds to this, including placing the journal note in a harder to view spot, but that often is then obscured to the players when they find the secret passage. Likewise, you can use journal notes only the GM can see, but that then doesn't give the players the ability to traverse the secret passage on their own and requires GM interaction to click the teleporter (not the end of the world).

**Comment by grandseiken** [comment] 2021-04-18 13:25
This is something I want to do, closing as a duplicate of #23 though.

**Closed by grandseiken** 2021-04-18 13:25 UTC
