### ISSUE TITLE
Memory leak when overlaying target/source?

### ISSUE THREAD

**Issue by SamF111** [grandseiken/foundryvtt-multilevel-tokens#5] opened 2020-07-09 12:25 UTC
I've found that the chrome window of my players runs out of memory when I have an overlapping drawing.
For a multiscene structure:
Level 1 sourceA
Level 2 targetA, source B
level 3 target B

I think it's occuring when target A+source B overlap.
I'm not expecting something from level 1 to be mirrored all the way to level 3, so I was happy with that not occuriring.
I was just being lazy defining my zones.

**Comment by grandseiken** [comment] 2020-07-24 15:20
I tried setting things up as you described, (two pairs of cloned regions where 1 source and 1 target are overlapping) and I couldn't reproduce any memory issues, do you have any more info / screenshot or steps to reproduce the problem?

**Comment by grandseiken** [comment] 2020-10-04 20:49
Closing since I couldn't reproduce, feel free to reopen if you have more info

**Closed by grandseiken** 2020-10-04 20:49 UTC
