### ISSUE TITLE
Error When Teleporting to Scenes

### ISSUE THREAD

**Issue by TXHobo** [grandseiken/foundryvtt-multilevel-tokens#94] opened 2021-06-06 22:03 UTC
I'm using 0.8.6 and latest 5E system version.  When i have a player move onto teleport to another scene area, it will usually work on the first teleport.  However, when the player tries to return they get an error saying they don't have a token with vision on the current scene and it is just dark for them.  If they reload, the scene appears and their token is there.  Here is the error i see in the console when it happens.
![MLT Error message](https://user-images.githubusercontent.com/85461616/120941604-1a8c1600-c6e9-11eb-9bc2-5ec87c8aa96d.PNG)

**Comment by grandseiken** [comment] 2022-09-03 01:33
Seems like a dupe of https://github.com/grandseiken/foundryvtt-multilevel-tokens/issues/103

**Closed by grandseiken** 2022-09-03 01:33 UTC
