### ISSUE TITLE
ENTER event not fired when player drags to move.

### ISSUE THREAD

**Issue by ChrisAndelin** [grandseiken/foundryvtt-multilevel-tokens#104] opened 2021-07-26 06:22 UTC
1. Make a Trigger ENTER event happen and prove it works by moving the player token with arrow keys into the trigger area
2. Start over and have the player move their character by clicking and dragging so their token moves over and past the trigger area.

Observe the player token slide right over the trigger area without firing the ENTER event.

**Comment by grandseiken** [comment] 2022-09-03 01:18
Dupe of https://github.com/grandseiken/foundryvtt-multilevel-tokens/issues/123 (yep, MLT only looks at positions tokens actually take, foundry movement animation is a purely visual effect)

**Closed by grandseiken** 2022-09-03 01:18 UTC
